version: '3'
services:
  nginx:
    image: nginx:1.14.0-alpine
    container_name: "laravel-nginx"
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/src

  php:
    build: ./php
    container_name: "laravel-php"
    env_file: .env
    environment:
      DATABASE_HOST: mysql
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/src

  mysql:
    image: mysql:5.7.19
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
